Authorization
mutinhiri/budget-app pull request #1
Opened 2022-03-23 22:09 UTC by mutinhiri

[Video Presentation](https://www.loom.com/share/693a07246eec4e0e875e85d7b1491ca7)
In this Pr i created a Ruby on Rails application that allows the user to:

-register and log in, so that the data is private to them.
-introduce new transactions associated with a category.
-see the money spent on each category.

2022-03-23 22:46 UTC, DeliceLydia requested changes
## Hi @mutinhiri, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! Major highlights for your project:
- Awesome video presentation
- App is working as expected
- Followed git worflows


## Required Changes ♻️
_Check the comments under the review._




### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-03-23 22:46 UTC, DeliceLydia commented on app/views/groups/_form.html.erb
> +  </div>
- [ ] Please Follow the [given design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=) that includes colors etc.. try to use only colors used in the design

2022-03-23 22:46 UTC, DeliceLydia commented on app/views/groups/new.html.erb
> +</div>
- [ ] Even the navbar should use only colors used in the design please address that

2022-03-23 22:46 UTC, DeliceLydia commented on app/views/investments/_form.html.erb
> +  </div>
- [ ] Same as here please use colors used in the design

2022-03-23 22:46 UTC, DeliceLydia commented on app/views/investments/index.html.erb
> +</div>
- [ ] Please use colors that were used in the [given design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=)

2022-03-23 22:46 UTC, DeliceLydia commented on README.md
> +## Acknowledgments
- [ ] Please give appropriate credit to [Gregoire Vella on Behance](https://www.behance.net/gregoirevella) the [author of the original design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=)

2022-03-24 00:42 UTC, DanSam5K approved these changes
Hi @mutinhiri ✌️ Approved ✌️ ,
- [x] Good job implementing the changes suggested ✔️ 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-24 06:17 UTC, merged